# Generated by Django 5.0 on 2024-09-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0013_alter_familia_acolhedora_forms_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="ptts_ouvidoria_maria_de_nazare",
            name="add_status",
            field=models.CharField(default="1", max_length=20),
        ),
    ]
